package de.rubenmaurer.price.core.parser.antlr

import de.rubenmaurer.price.antlr4.{IRCBaseListener, IRCParser}
import de.rubenmaurer.price.core.facade.Parser.ParseData
import de.rubenmaurer.price.util.TemplateManager

/**
 * Listener for walking the syntax tree generated by ANTLR.
 *
 * @param parseData The optional data for content validation.
 */
class PricefieldListener(parseData: ParseData) extends IRCBaseListener {

  /**
   * List of all parser errors.
   */
  var errors: List[String] = List()

  /**
   * Enter server_response_short.
   **/
  override def enterServer_response_short(ctx: IRCParser.Server_response_shortContext): Unit = {
    stringCheck(ctx.nick().getText, parseData.nick, ctx.getText)
    stringCheck(ctx.user().getText, parseData.user, ctx.getText)
  }

  /**
   * Enter quit.
   */
  override def enterQuit(ctx: IRCParser.QuitContext): Unit = {
    stringCheck(ctx.message().getText, parseData.message, ctx.getText)
  }

  /**
   * Enter private_message.
   */
  override def enterPrivate_message(ctx: IRCParser.Private_messageContext): Unit = {
    stringCheck(ctx.message().getText, parseData.message, ctx.getText)
  }

  /**
   * Enter notice.
   *    */
  override def enterNotice(ctx: IRCParser.NoticeContext): Unit = {
    stringCheck(ctx.message().getText, parseData.message, ctx.getText)
  }

  /**
   * Enter unknown_command.
   *    */
  override def enterUnknown_command(ctx: IRCParser.Unknown_commandContext): Unit = {
    stringCheck(ctx.command().getText, parseData.command, ctx.getText)
  }

  /**
   * Enter motd.
   *    */
  override def enterMotd(ctx: IRCParser.MotdContext): Unit = {
    stringCheck(ctx.message().getText, parseData.message, ctx.getText)
  }

  /**
   * Enter nick_reply.
   *    */
  override def enterNick_reply(ctx: IRCParser.Nick_replyContext): Unit = {
    stringCheck(ctx.nick().getText, parseData.message, ctx.getText)
  }

  /* === WHO === */

  /**
   * Enter who.
   *    */
  override def enterWho(ctx: IRCParser.WhoContext): Unit = {
    if (parseData.channel != "*") stringCheck(ctx.target().getText, parseData.channel, ctx.getText)

    stringCheck(ctx.nick().getText, parseData.nick, ctx.getText)
    stringCheck(ctx.user().getText, parseData.user, ctx.getText)
    stringCheck(ctx.fullname().getText, parseData.fullname, ctx.getText)
  }

  /**
   * Enter end_of_who.
   *    */
  override def enterEnd_of_who(ctx: IRCParser.End_of_whoContext): Unit = {
    if (parseData.channel != "*") stringCheck(ctx.target().getText, parseData.channel, ctx.getText)
  }

  /* === TOPIC === */

  /**
   * Enter topic.
   *    */
  override def enterTopic(ctx: IRCParser.TopicContext): Unit = {
    stringCheck(ctx.channel().getText, parseData.channel, ctx.getText)
    stringCheck(ctx.message().getText, parseData.message, ctx.getText)
  }

  /**
   * Enter no_topic.
   *    */
  override def enterNo_topic(ctx: IRCParser.No_topicContext): Unit = {
    stringCheck(ctx.channel().getText, parseData.channel, ctx.getText)
  }

  /* === CHANNEL/ NICK ERROR ===*/

  /**
   * Enter no_such_nick_channel.
   *    */
  override def enterNo_such_nick_channel(ctx: IRCParser.No_such_nick_channelContext): Unit = {
    stringCheck(ctx.target().getText, parseData.target, ctx.getText)
  }

  /**
   * Enter cannot_send_to_channel.
   *    */
  override def enterCannot_send_to_channel(ctx: IRCParser.Cannot_send_to_channelContext): Unit = {
    stringCheck(ctx.channel().getText, parseData.channel, ctx.getText)
  }

  /* === PART === */

  /**
   * Enter part.
   *    */
  override def enterPart(ctx: IRCParser.PartContext): Unit = {
    stringCheck(ctx.channel().getText, parseData.channel, ctx.getText)
    stringCheck(ctx.message().getText, parseData.message, ctx.getText)
  }

  /* === LIST === */

  /**
   * Enter list.
   *    */
  override def enterList(ctx: IRCParser.ListContext): Unit = {
    stringCheck(ctx.channel().getText, parseData.channel, ctx.getText)
    integerCheck(ctx.INTEGER().getText, parseData.clients, ctx.getText)
    stringCheck(ctx.message().getText, parseData.message, ctx.getText)
  }

  /* === NAME LIST ===*/

  /**
   * Enter name_reply.
   *    */
  override def enterName_reply(ctx: IRCParser.Name_replyContext): Unit = {
    stringCheck(ctx.channel().getText, parseData.channel, ctx.getText)
    stringCheck(ctx.nicknames().getText, s"@${parseData.names.mkString(" ")}", ctx.getText)
  }

  /**
   * Enter end_of_names.
   *    */
  override def enterEnd_of_names(ctx: IRCParser.End_of_namesContext): Unit = {
    stringCheck(ctx.channel().getText, parseData.channel, ctx.getText)
  }

  /* === WHOIS === */

  /**
   * Enter who_is_user.
   *    */
  override def enterWho_is_user(ctx: IRCParser.Who_is_userContext): Unit = {
    stringCheck(ctx.nick().getText, parseData.nick, ctx.getText)
    stringCheck(ctx.user().getText, parseData.user, ctx.getText)
    stringCheck(ctx.fullname().getText, parseData.fullname, ctx.getText)
  }

  /**
   * Enter who_is_server.
   *    */
  override def enterWho_is_server(ctx: IRCParser.Who_is_serverContext): Unit = {
    stringCheck(ctx.nick().getText, parseData.nick, ctx.getText)
  }

  /**
   * Enter end_of_who_is.
   *    */
  override def enterEnd_of_who_is(ctx: IRCParser.End_of_who_isContext): Unit = {
    stringCheck(ctx.nick().getText, parseData.nick, ctx.getText)
  }

  /* === LUSER === */

  /**
   * Enter luser_client.
   *    */
  override def enterLuser_client(ctx: IRCParser.Luser_clientContext): Unit = {
    integerCheck(ctx.INTEGER(0).getText, parseData.clients, ctx.getText)
  }

  /**
   * Enter luser_unknown.
   *    */
  override def enterLuser_unknown(ctx: IRCParser.Luser_unknownContext): Unit = {
    integerCheck(ctx.INTEGER.getText, parseData.unknown, ctx.getText)
  }

  /**
   * Enter luser_channel.
   *    */
  override def enterLuser_channel(ctx: IRCParser.Luser_channelContext): Unit = {
    integerCheck(ctx.INTEGER.getText, parseData.channels, ctx.getText)
  }

  /**
   * Enter luser_me.
   *    */
  override def enterLuser_me(ctx: IRCParser.Luser_meContext): Unit = {
    integerCheck(ctx.INTEGER(0).getText, parseData.users, ctx.getText)
  }

  /* === VALUE CHECKS === */

  /**
   * Compares to strings.
   *
   * @param expected The expected string.
   * @param actual The actual string.
   * @param line The line from which the actual string is.
   */
  def stringCheck(expected: String, actual: String, line: String): Unit = {
    if (!expected.equals(actual)) {
      errors = TemplateManager.getCompareFailure("String", actual, line) :: errors
    }
  }

  /**
   * Compares two integers.
   *
   * @param expected The expected integer as string.
   * @param actual The actual integer.
   * @param line The line from which the actual integer is.
   */
  def integerCheck(expected: String, actual: Int, line: String): Unit = integerCheck(expected.toInt, actual, line)

  /**
   * Compares to integers.
   *
   * @param expected The expected integer.
   * @param actual The actual integer.
   * @param line The line from which the actual integer is.
   */
  def integerCheck(expected: Int, actual: Int, line: String): Unit = {
    if (expected != actual) {
      errors = TemplateManager.getCompareFailure("Integer", actual, line) :: errors
    }
  }
}